### PR TITLE
Move command line arguments to YAML configuration file

### PR DESCRIPTION
**Pull request by saparikh**
Moved all existing command line args to a YAML configuration file, except:
--log-level

Added command line arg for specifying the configuration file:
--config-file

Also added sample YAML configuration file.

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/50)

### CODE REVIEW

**Comment by ratulm** [comment]
It looks like this PR removes the ability to specify arguments on the command line completely. Is that right? I am not sure if that is desirable because command line arguments are easier to specify than config files and are more suited to fast, experimental use. What you probably want to do is to retain the command line arguments and use what is specified there to override what is in the config file if certain arguments are provided in both places.

**Comment by dhalperi** [comment]
+1 @ratul's comment. Similarly, no reason not to put log-level in the config file as a default.

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/intentionet/netconan/50#-L6yzoDzOEJvdhmX1z-_:-L6yzoDzOEJvdhmX1z-a:b41bvis) (no related file):*
Adding blocking comment re: preserving CLI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
Reviewed 2 of 3 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/intentionet/netconan/50#-L6yzoDzOEJvdhmX1z-_:-L75mrE6C17o6buNWiXO:bs9jhhm) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Adding blocking comment re: preserving CLI
</blockquote></details>

Rather than reinventing the wheel, should we just use the standard Python way to do this?

https://stackoverflow.com/a/5826167/1715495

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/50)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/intentionet/netconan/50#-L6yzoDzOEJvdhmX1z-_:-L75riVn2tNiTX3BwfsM:bc7d72g) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Rather than reinventing the wheel, should we just use the standard Python way to do this?

https://stackoverflow.com/a/5826167/1715495
</blockquote></details>

This is cool! I didn't know about it. 

The only reason to keep it this way would be to preserve the yaml format for the config file (which folks asked for and are familiar with). Is that a good reason? I could go either way. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/intentionet/netconan/50#-L6yzoDzOEJvdhmX1z-_:-L75sY-q0XGFgmozbh6F:b-1c0plk) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

This is cool! I didn't know about it. 

The only reason to keep it this way would be to preserve the yaml format for the config file (which folks asked for and are familiar with). Is that a good reason? I could go either way. 
</blockquote></details>

I'm betting YAML was meant as an example not a specific technology choice. The Python config files seem perfectly manually editable to me, so would prefer to just use the standard code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
Reviewed 2 of 4 files at r4.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76SoY7mfc9uGorjKxA:-L76SoY7mfc9uGorjKxB:blm0c2e) (no related file):*
Okay, I added testing and a few bug fixes to @ratul 's version. (What a group party!)

Ratul, can you review my code for sanity? (It should be the unreviewed diffs).

Victor, can you review the tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76SoY7mfc9uGorjKxA:-L76T3gYl5123Wx2W6Lu:b-2ovizc) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Okay, I added testing and a few bug fixes to @ratul 's version. (What a group party!)

Ratul, can you review my code for sanity? (It should be the unreviewed diffs).

Victor, can you review the tests?
</blockquote></details>

@progwriter  ^^

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by sfraint** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[sample-netconan-config.cfg, line 9 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76HGRu97qcAR0VCJKc:-L76HGRu97qcAR0VCJKd:b-xt2w3o) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/sample-netconan-config.cfg#L9)):*
> ```INI
> salt=BLAHBLAHBLAH
> dump_ip_map=./ip-map-file
> sensitive_words=TEST1 TEST2 TEST3 TEST4
> ```

This sample param may be a little misleading.  Netconan will see `TEST1 TEST2 TEST3 TEST4` as a single keyword and replace all occurrences of that full string, while a user might interpret this as trying to replace each of those words separately.

---

*[netconan/netconan.py, line 64 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76GhTn7tl8GBzzNL5g:-L76GhTn7tl8GBzzNL5h:b-qlhkzc) ([raw file](https://github.com/intentionet/netconan/blob/8326e4248412a9f209f36d81ee58ff6620787d16/netconan/netconan.py#L64)):*
> ```Python
>     sensitive_words = None
>     if options.sensitive_words is not None:
>         sensitive_words = options.sensitive_words.split(',')
> ```

Was removing this intentional?  I think this will break sensitive words.

---

*[netconan/netconan.py, line 77 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76LFnrCcU3NITsk4we:-L76LFnrCcU3NITsk4wf:bub4guq) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/netconan/netconan.py#L77)):*
The syntax of `-a`, `-p`, and `-u` (the `'store_true'` flags) has changed.
Previously, those params did not require any value to be supplied, i.e. this was valid:
> netconan -a -i ./in -o ./out

But now it would need to be:
> netconan -a true -i ./in -o ./out

So either 1) documentation (readme) should be updated the reflect the change in these params, or 2) they should be reverted to behave like they did before.

---

*[netconan/netconan.py, line 94 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76S28oqtkOlArgdzMo:-L76S28oqtkOlArgdzMp:bjnjhde) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/netconan/netconan.py#L94)):*
> ```Python
>     parser.add_argument('-u', '--undo', type=str2bool,
>                         help='Undo reversible anonymization (must specify salt)')
>     parser.add_argument('-w', '--sensitive-words', nargs="+",
> ```

This changes the syntax of `sensitive-words` param, so the readme should be updated

---

*[netconan/netconan.py, line 98 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76NhxLTxrQf7Giwzv0:-L76NhxLTxrQf7Giwzv1:b-b6q29e) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/netconan/netconan.py#L98)):*
> ```Python
>     args = parser.parse_args(remaining_argv)
> 
>     print(args)
> ```

Is this intentionally left in?

---

*[netconan/netconan.py, line 116 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76OPJFU95K3anfXeyl:-L76OPJFU95K3anfXeym:bocsrwj) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/netconan/netconan.py#L116)):*
> ```Python
> 
>     if not os.path.exists(args.output):
>         os.makedirs(args["output"])
> ```

I would change this to `os.makedirs(args.output)` for consistency (also not sure if the above works)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by sfraint** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[sample-netconan-config.cfg, line 9 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76HGRu97qcAR0VCJKc:-L76VF7Kv5eQ85lQDLnU:b-qm9kq0) ([raw file](https://github.com/intentionet/netconan/blob/57fdba07a565dc52dd5df2b232959d2f88581720/sample-netconan-config.cfg#L9)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

This sample param may be a little misleading.  Netconan will see `TEST1 TEST2 TEST3 TEST4` as a single keyword and replace all occurrences of that full string, while a user might interpret this as trying to replace each of those words separately.
</blockquote></details>

Actually, this might be seen as an array of characters, each character being considered a "sensitive word"

---

*[netconan/netconan.py, line 64 at r4](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76GhTn7tl8GBzzNL5g:-L76VAhevUL7jeT_SNDx:b-vfhj3z) ([raw file](https://github.com/intentionet/netconan/blob/8326e4248412a9f209f36d81ee58ff6620787d16/netconan/netconan.py#L64)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Was removing this intentional?  I think this will break sensitive words.
</blockquote></details>

Never mind, ignore this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by dhalperi** [comment]
*[sample-netconan-config.cfg, line 6 at r5](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76bhqQpiufagMmUrwv:-L76bhqQpiufagMmUrww:bkx95rb) ([raw file](https://github.com/intentionet/netconan/blob/aee26ad201b6760ed865fdf3f16c28c5a2b7b967/sample-netconan-config.cfg#L6)):*
> ```INI
> log_level=INFO
> anonymize_ips=True
> anonymize_passwords=True
> ```

another bad thing with current implementation is that the constant names in config file do not match argument names (e.g., `--anonymize-passwords` vs `anonymize_passwords`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Comment by progwriter** [comment]
Reviewed 1 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76SoY7mfc9uGorjKxA:-L76kl6Y-Eyhchp1FgZ0:b-ndcx3r) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@progwriter  ^^
</blockquote></details>

Tests look fine, although I did leave a different comment

---

*[netconan/netconan.py, line 44 at r5](https://reviewable.io:443/reviews/intentionet/netconan/50#-L76gYOJykhddCG8ELCc:-L76gYOJykhddCG8ELCd:bd0wfxe) ([raw file](https://github.com/intentionet/netconan/blob/aee26ad201b6760ed865fdf3f16c28c5a2b7b967/netconan/netconan.py#L44)):*
> ```Python
>         # Turn off help, so that the parser below prints help for all options.
>         add_help=False
>     )
> ```

To me this looks overly complex: multiple parsers, multiple places defaults are initialized (both dict and in `parser`)? 
Why not simply:
- Initialize a settings dictionary with default values
- Parse args (single argument parser, with '-c','--config' being an optional parameter)
- If '-c' is present, (i.e., not `None`) read the config file and update settings dictionary
- Update dictionary with any other command line args that are present (just take care to logically OR any args that have `action='store_true'`, speaking to Spencer's comment below)
- Return the final settings dictionary (optionally as AttrDict to support dot notation in `main`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/50)*

**Pull request closed without merging**
