### PR TITLE
netconan: require python 3.7+

### PR DESCRIPTION
**Pull request by dhalperi**
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/174)

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/174)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @sfraint)

___
*[netconan/ip_anonymization.py, line 77 at r1](https://reviewable.io/reviews/intentionet/netconan/174#-MqGhIn2ASg8tF-YCU4T:-MqGhIn2ASg8tF-YCU4U:bjtez6) ([raw file](https://github.com/intentionet/netconan/blob/79ad51d102ff2fd0ef8935047b8b82c4ef15d8b0/netconan/ip_anonymization.py#L77)):*
> ```Python
> def _ensure_unicode(str):
>     if not isinstance(str, text_type):
>         str = u(str)
> ```

FYI `u(x)` is `return x` on python 3, so this whole function is a no-op.

https://github.com/benjaminp/six/blob/master/six.py#L642-L646
___
*[netconan/sensitive_item_removal.py, line 258 at r1](https://reviewable.io/reviews/intentionet/netconan/174#-MqGhX9Q7oF_vSPc-QSW:-MqGhX9Q7oF_vSPc-QSX:b-ntsef8) ([raw file](https://github.com/intentionet/netconan/blob/26d96d85ef9ee768a388087232a7d41c6df9c404/netconan/sensitive_item_removal.py#L258)):*
> ```
> anon_val.encode()
> ```

FYI `b` is `.encode("latin-1")`, but for the strings involved this should make no difference. https://github.com/benjaminp/six/blob/master/six.py#L642-L646

**Review by sfraint — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/174)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[setup.py, line 69 at r2](https://reviewable.io/reviews/intentionet/netconan/174#-MqGnt5zCIGHA_YslvWW:-MqGnt5zCIGHA_YslvWX:b-nvu8pe) ([raw file](https://github.com/intentionet/netconan/blob/b671d23d35158353353dbcbc47a718b571cbb0fc/setup.py#L69)):*
> ```
>         "Programming Language :: Python :: 3.10",
> ```
add `3.10` in travis config too?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/174)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[setup.py, line 69 at r2](https://reviewable.io/reviews/intentionet/netconan/174#-MqGnt5zCIGHA_YslvWW:-MqGo_RT6enm9mrQjFGo:b-jbhpu5) ([raw file](https://github.com/intentionet/netconan/blob/b671d23d35158353353dbcbc47a718b571cbb0fc/setup.py#L69)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>         "Programming Language :: Python :: 3.10",
> ```
add `3.10` in travis config too?
</blockquote></details>

Ahh missed this in R2.

Python 3.10 is not testable in travis :p

removed.

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/174)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[setup.py, line 69 at r2](https://reviewable.io/reviews/intentionet/netconan/174#-MqGnt5zCIGHA_YslvWW:-MqGuBZL61s6O7y7L7Wj:b4c9lyr) ([raw file](https://github.com/intentionet/netconan/blob/b671d23d35158353353dbcbc47a718b571cbb0fc/setup.py#L69)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ahh missed this in R2.

Python 3.10 is not testable in travis :p

removed.
</blockquote></details>

:thumbsup:

**Pull request merged**
