### PR TITLE
Added AS number anonymization

### PR DESCRIPTION
**Pull request by sfraint**
* Added AS number anonymization option
* Updated readme
* Added tests

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/53)

### CODE REVIEW

**Comment by progwriter** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[netconan/sensitive_item_removal.py, line 63 at r1](https://reviewable.io:443/reviews/intentionet/netconan/53#-L7k2Hsvx3s2uMWFawZB:-L7k2HswglWGKTSimpVe:b-xvfxiv) ([raw file](https://github.com/intentionet/netconan/blob/14d1a5185f277450bb6ceb1ef64ba446fce1168c/netconan/sensitive_item_removal.py#L63)):*
> ```Python
>         if original in line:
>             replacement = _anonymize_as_num(original, salt)
>             line = line.replace(original, replacement)
> ```

You can probably pre-compute the replacements once per run. (e.g., a dictionary mapping old AS value to new AS value) and then pre-compile a regex and do replacements in one swoop (e.g, https://stackoverflow.com/questions/2400504/easiest-way-to-replace-a-string-using-a-dictionary-of-replacements).

This will probably get you speedups both because 1) not doing crypto hashes foreach line, and 2) because compiled regex-replace is only executed once per line, not `num_as_numbers * num_lines`.

That said, I don't think perf is a problem now. Just FYI, this comment is non-blocking.

---

*[tests/test_sensitive_item_removal.py, line 218 at r1](https://reviewable.io:443/reviews/intentionet/netconan/53#-L7k1jpvzXH6DQrWoKLW:-L7k1jpvzXH6DQrWoKLX:b-f6qej8) ([raw file](https://github.com/intentionet/netconan/blob/14d1a5185f277450bb6ceb1ef64ba446fce1168c/tests/test_sensitive_item_removal.py#L218)):*
> ```Python
> def test_as_number_invalid(invalid_as_number):
>     """Test that exception is thrown with invalid AS number."""
>     with pytest.raises(Exception):
> ```

Probably good idea to not generalize the exception? You are legitimately only expecting a `ValueError` here, that you know you raised, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/53)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[netconan/sensitive_item_removal.py, line 63 at r1](https://reviewable.io:443/reviews/intentionet/netconan/53#-L7k2Hsvx3s2uMWFawZB:-L7kBC_UxfaMd82Ni02X:bv8yj1a) ([raw file](https://github.com/intentionet/netconan/blob/14d1a5185f277450bb6ceb1ef64ba446fce1168c/netconan/sensitive_item_removal.py#L63)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

You can probably pre-compute the replacements once per run. (e.g., a dictionary mapping old AS value to new AS value) and then pre-compile a regex and do replacements in one swoop (e.g, https://stackoverflow.com/questions/2400504/easiest-way-to-replace-a-string-using-a-dictionary-of-replacements).

This will probably get you speedups both because 1) not doing crypto hashes foreach line, and 2) because compiled regex-replace is only executed once per line, not `num_as_numbers * num_lines`.

That said, I don't think perf is a problem now. Just FYI, this comment is non-blocking.
</blockquote></details>

re: precomputing replacements, done.

re: regex, I think multiple `string.replace`s will be similar speed (or maybe still faster) than regex matching in this case, so just going to leave it as is

---

*[tests/test_sensitive_item_removal.py, line 218 at r1](https://reviewable.io:443/reviews/intentionet/netconan/53#-L7k1jpvzXH6DQrWoKLW:-L7kBiaYQMuiTQWQQ6yc:b-48vilg) ([raw file](https://github.com/intentionet/netconan/blob/14d1a5185f277450bb6ceb1ef64ba446fce1168c/tests/test_sensitive_item_removal.py#L218)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Probably good idea to not generalize the exception? You are legitimately only expecting a `ValueError` here, that you know you raised, right?
</blockquote></details>

Good call, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/53)*

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/53#-:-L7kELeG26UwROPC253r:bnfp4nl)*

**Comment by dhalperi** [comment]
*[tests/test_sensitive_item_removal.py, line 155 at r2](https://beta.reviewable.io/reviews/intentionet/netconan/53#-L7lJK8F6FlLVF3-8wno:-L7lJK8F6FlLVF3-8wnp:b-qfiiyi) ([raw file](https://github.com/intentionet/netconan/blob/b5cd7873eb6a92009ec3fbfb1154993eea876841/tests/test_sensitive_item_removal.py#L155)):*
> ```Python
>     ('something {} something', ['123']),
>     ('123{}890', ['65530']),
>     ('123{0}890 and {0} again', ['65530']),
> ```

the left example here should not be anonymized.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/53)*

**Comment by dhalperi** [comment]
*[netconan/sensitive_item_removal.py, line 62 at r2](https://beta.reviewable.io/reviews/intentionet/netconan/53#-L7lJGNB7IDi7hhrRQ32:-L7lJGNB7IDi7hhrRQ33:bqwe3k6) ([raw file](https://github.com/intentionet/netconan/blob/b5cd7873eb6a92009ec3fbfb1154993eea876841/netconan/sensitive_item_removal.py#L62)):*
> ```Python
>     for original in as_number_map:
>         if original in line:
>             line = line.replace(original, as_number_map[original])
> ```

Do all these substitions in one go like we did somewhere else.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/53)*

**Pull request merged**
