### PR TITLE
Python2 support

### PR DESCRIPTION
**Pull request by sfraint**
* Added unicode check in ip anonymization
* Added e2e test

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/58)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 11 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[setup.cfg, line 19 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HoU1F4NO6xaz0HGDX:-L9HoU1G4jJcYIwsGZT_:bioj640) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/setup.cfg#L19)):*
> ```INI
> [tool:pytest]
> addopts = --cov=netconan
> testpaths=tests/unit tests/end_to_end
> ```

is this needed or will it auto-discover given only `tests` ?

---

*[tests/end_to_end/test_end_to_end.py, line 40 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpBCUEKpBvq2X-ji0:-L9HpBCUEKpBvq2X-ji1:b-7sjkpe) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/end_to_end/test_end_to_end.py#L40)):*
> ```Python
> 
>     filename = "test.txt"
>     input_dir = str(tmpdir.mkdir("input"))
> ```

Is there a pytest-specific way to clean up temp files when done? Right now, looks like the temp data will be left there.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by progwriter** [comment]
Reviewed 6 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9HpjJ24uRWXX7VxJBp:bddu79m) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
> ```Python
>     def make_addr(cls, addr_str):
>         """Return an IPv6 address from the given string."""
>         if not isinstance(addr_str, text_type):
> ```

Avoid duplication, pull out into a func like `ensure_unicode`?

---

*[tests/end_to_end/test_end_to_end.py, line 40 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpBCUEKpBvq2X-ji0:-L9HpgK6A-jB-xzTXjMP:b5odoc5) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/end_to_end/test_end_to_end.py#L40)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is there a pytest-specific way to clean up temp files when done? Right now, looks like the temp data will be left there.
</blockquote></details>

See https://docs.pytest.org/en/latest/tmpdir.html

---

*[tests/unit/test_sensitive_item_removal.py, line 121 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpMiFDi2ZC3wZlVpa:-L9HpMiFDi2ZC3wZlVpb:bwa9qti) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/unit/test_sensitive_item_removal.py#L121)):*
> ```Python
> ]
> 
> misc_password_lines = [
> ```

Is this intentional? just curious, doesn't seem related to py2/3 compat.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by dhalperi** [comment]
*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9HrvTW-8DSxpe67vvt:b-exx8h9) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Avoid duplication, pull out into a func like `ensure_unicode`?
</blockquote></details>

To be fair, I bet that `u` is what you'd think `ensure_unicode` is.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by progwriter** [comment]
*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9HsIqeAOsiPfM0RRIT:b-1wtq5y) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

To be fair, I bet that `u` is what you'd think `ensure_unicode` is.
</blockquote></details>

Not quite. `u` will crash if `addr_str` is already unicode :wink: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by dhalperi** [comment]
*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9HsajM758WUeyjJfdW:b56uf8h) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Not quite. `u` will crash if `addr_str` is already unicode :wink: 
</blockquote></details>

:eyeroll:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by dhalperi** [comment]
*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9HsceT8nnKLHu_pby7:b4c9lyr) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

:eyeroll:
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[setup.cfg, line 19 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HoU1F4NO6xaz0HGDX:-L9I4VGdAxr9eqGIS9dd:b-3frmrb) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/setup.cfg#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this needed or will it auto-discover given only `tests` ?
</blockquote></details>

Not needed, removed.

---

*[netconan/ip_anonymization.py, line 207 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpjJ24uRWXX7VxJBo:-L9I5MmPEJjh2ygKrRAP:b-896fix) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/netconan/ip_anonymization.py#L207)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.

---

*[tests/end_to_end/test_end_to_end.py, line 40 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpBCUEKpBvq2X-ji0:-L9IBpZv1vJJkn2-PmL6:bdl3b09) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/end_to_end/test_end_to_end.py#L40)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

See https://docs.pytest.org/en/latest/tmpdir.html
</blockquote></details>

Looks like the tmpdir is cleaned up, pytest just keeps a few of the most recent versions around: https://github.com/pytest-dev/pytest/issues/543 (though the suggestion on changing number of versions kept does not appear to work for me)

---

*[tests/unit/test_sensitive_item_removal.py, line 121 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9HpMiFDi2ZC3wZlVpa:-L9I46e28_eT0YaQcTAC:bm9mzzl) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/unit/test_sensitive_item_removal.py#L121)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Is this intentional? just curious, doesn't seem related to py2/3 compat.
</blockquote></details>

Not really related, just added a password test case I realized wasn't covered when I wrote the end to end test.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by progwriter** [comment]
Reviewed 4 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[netconan/ip_anonymization.py, line 112 at r2](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9IFIr-APItSDHq3LQk:-L9IFIr-APItSDHq3LQl:b-rksqnd) ([raw file](https://github.com/intentionet/netconan/blob/15e8ce897a52e07be2a83415684e643fccd9da28/netconan/ip_anonymization.py#L112)):*
> ```Python
> 
>     @classmethod
>     def ensure_unicode(cls, str):
> ```

I do not think this is a class method. Isn't it just a file-private utility method?

I think it probably goes up as a function where `_generate_bit_from_hash` is.

---

*[tests/end_to_end/test_end_to_end.py, line 43 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9IGJjP-SbR9NVbd3mx:-L9IGJjP-SbR9NVbd3my:bptamdv) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/end_to_end/test_end_to_end.py#L43)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     filename = "test.txt"
>     input_dir = str(tmpdir.mkdir("input"))
>     input_file = path.join(input_dir, filename)
>     with open(input_file, 'w') as f_tmp:
>         f_tmp.write(input_contents)
> ```
</details>


Why do you do so much string/path back and forth conversion? Is this complexity necessary?

The standard pytest example looks much simpler:

```py
p = tmpdir.mkdir("sub").join("hello.txt")
p.write("content")
```

So,

```py
filename = "test.txt"
input_file = tmpdir.mkdir("input").join(filename)
input_file.write(input_content)
```

Generally, my understanding is that the return values of the `tmpdir` functions should be usable as filenames or file-like objects.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[netconan/ip_anonymization.py, line 112 at r2](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9IFIr-APItSDHq3LQk:-L9IIHNK49fj92r0Bb2z:b-896fix) ([raw file](https://github.com/intentionet/netconan/blob/15e8ce897a52e07be2a83415684e643fccd9da28/netconan/ip_anonymization.py#L112)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I do not think this is a class method. Isn't it just a file-private utility method?

I think it probably goes up as a function where `_generate_bit_from_hash` is.
</blockquote></details>

Done.

---

*[tests/end_to_end/test_end_to_end.py, line 43 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/58#-L9IGJjP-SbR9NVbd3mx:-L9IJ7twAqUMuBr03eu7:b-rxe12j) ([raw file](https://github.com/intentionet/netconan/blob/d9318664c859aa93a852e735d6caf98904f49afb/tests/end_to_end/test_end_to_end.py#L43)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     filename = "test.txt"
>     input_dir = str(tmpdir.mkdir("input"))
>     input_file = path.join(input_dir, filename)
>     with open(input_file, 'w') as f_tmp:
>         f_tmp.write(input_contents)
> ```

Why do you do so much string/path back and forth conversion? Is this complexity necessary?

The standard pytest example looks much simpler:

```py
p = tmpdir.mkdir("sub").join("hello.txt")
p.write("content")
```

So,

```py
filename = "test.txt"
input_file = tmpdir.mkdir("input").join(filename)
input_file.write(input_content)
```

Generally, my understanding is that the return values of the `tmpdir` functions should be usable as filenames or file-like objects.
</blockquote></details>

We just need to access the dirs and files as strings for `netconan` and `filecmp`.
I've cleaned it up a little.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58#-:-L9IToak0CWBYu-FvLlv:bnfp4nl)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/58#-:-L9I_YlgD2AeFjQXSwn9:bnfp4nl)*

**Pull request merged**
