### PR TITLE
Add ability to specify args in config file

### PR DESCRIPTION
**Pull request by sfraint**
Add ability to specify args in config file.
* Using `configargparse` for simplicity of arg parsing code
* Allows combination of command line and config file args (command line args override config which override default)

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/51)

### CODE REVIEW

**Comment by saparikh** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/51#-:-L7B8Bdz98_6NMX6u8RR:bnfp4nl)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 92 at r5](https://reviewable.io:443/reviews/intentionet/netconan/51#-L7B8jYkzZPFv2imdsWb:-L7B8jYkzZPFv2imdsWc:bxquawz) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L92)):*
> -a

does not start with `--`

---

*[README.rst, line 94 at r5](https://reviewable.io:443/reviews/intentionet/netconan/51#-L7B8oY3xLEDsDBkH-ff:-L7B8oY3xLEDsDBkH-fg:bx7e5lx) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L94)):*
> https://goo.gl/R74nmi

Use a RST link here.

---

*[README.rst, line 96 at r5](https://reviewable.io:443/reviews/intentionet/netconan/51#-L7B8ubfBd5Xg6r9qk3D:-L7B8ubfBd5Xg6r9qk3E:b7rpq1u) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L96)):*
> ```reStructuredText
>     details, see syntax at https://goo.gl/R74nmi). If an arg is specified in more
>     than one place, then commandline values override config file values which
>     override defaults.
> ```

Move this paragraph below the `--`-explanation right below this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/51#-:-L7B9WgugCkb5BHqDzWQ:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 92 at r5](https://beta.reviewable.io/reviews/intentionet/netconan/51#-L7B8jYkzZPFv2imdsWb:-L7BAKbn26aLCdTThkap:bg4a9q4) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L92)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> -a

does not start with `--`
</blockquote></details>

This help message is generated by `configargparse`.  I can see if there is an easy way to change parts of it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/51)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 94 at r5](https://beta.reviewable.io/reviews/intentionet/netconan/51#-L7B8oY3xLEDsDBkH-ff:-L7BGaHf8WQjjjNpgjty:bmkxblf) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L94)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> https://goo.gl/R74nmi

Use a RST link here.
</blockquote></details>

It looks like you cannot put links in RST code blocks, so I've added a link above the help code block.

---

*[README.rst, line 96 at r5](https://beta.reviewable.io/reviews/intentionet/netconan/51#-L7B8ubfBd5Xg6r9qk3D:-L7BI4gE7SkulolpagIK:b8m2rw5) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L96)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Move this paragraph below the `--`-explanation right below this?
</blockquote></details>

Changed the ordering a little, is that what you meant?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/51)*

**Comment by dhalperi** [comment]
*[README.rst, line 92 at r5](https://beta.reviewable.io/reviews/intentionet/netconan/51#-L7B8jYkzZPFv2imdsWb:-L7BQgT03NfZ_LpWPyE_:b-yfvj3r) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L92)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

This help message is generated by `configargparse`.  I can see if there is an easy way to change parts of it.
</blockquote></details>

Hmm, I did not realize this entire block was just the help file as-is. Probably revert to what it was, and then we can take a look.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/51)*

**Comment by dhalperi** [comment]
*[README.rst, line 92 at r5](https://reviewable.io:443/reviews/intentionet/netconan/51#-L7B8jYkzZPFv2imdsWb:-L7BTXwNWYlpeZ954_q3:bzc7myu) ([raw file](https://github.com/intentionet/netconan/blob/8259d0b48997c206ba8c27ee045c7df13accb9bc/README.rst#L92)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Hmm, I did not realize this entire block was just the help file as-is. Probably revert to what it was, and then we can take a look.
</blockquote></details>

Never mind. your solution is still the description as-is!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/51)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/51#-:-L7BTeuNO6pMp51n5IKM:bnfp4nl)*

**Pull request merged**
