### PR TITLE
Allow for anonymization of in-memory configurations

### PR DESCRIPTION
**Pull request by Kircheneer**
- Introduce `build_anonymizers` function to centralize configuration logic
- Introduce `anonymize_configuration` function to anonymize configurations in memory
- Reduce newly created code duplication by using `anonymize_configuration` to anonymize configuration in files
- Write a test for this

- - -
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)

### CODE REVIEW

**Comment by Kircheneer** [comment]
Why? I am building something for which I want to anonymize configurations before I even have them on the disk, as I never want them on the disk un-anonymized.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Kircheneer and @sfraint)

*[a discussion](https://reviewable.io/reviews/intentionet/netconan/186#-NW63adK1K8M-y3TLa1q:-NW63adK1K8M-y3TLa1r:b-8ngyvi) (no related file):*
This looks cool, thanks for the contribution. A few notes:

1. We didn't quite have our new GitHub-based CI setup to run on PRs, fixed now. I merged the updated config in, and it found a bunch of style issues. Most were fixed automatically (`pre-commit run --all-files`), please take a pass.

2. I'd recommend a simpler / less invasive approach that doesn't require quite so much boilerplate. TL;DR:
    - introduce a (private-ish) class that is a SingleFileAnonymizer. That class will be the single source of truth for all these settings, and also only do the logic ones.
    - give it an anonymize_io(in_io, out_io) function that does the work
    - make the existing function create the class once and then recursively call `anonymize_io` using file IO objects
    - make your new function create the class once and call it with StringIO (or BytesIO, I forget which)

Seems like this approach would be simpler because we'd eliminate the need for this new kwargs dictionary as well as provide reusability.

___

**Comment by Kircheneer** [comment]
Thanks for the quick review! I believe I have addressed all your concerns and the CI should pass - I ran `pre-commit run --all-files` locally and there were no issues.

Let me know if this matched your desired design now.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)* status: all files reviewed, 2 unresolved discussions (waiting on @Kircheneer and @sfraint)

___
*[`tests/unit/test_anonymize_files.py` line 9 at r3](https://reviewable.io/reviews/intentionet/netconan/186#-NW93NwC6SWSOAnpv0Ih:-NW93NwC6SWSOAnpv0Ii:b-5t9r8) ([raw file](https://github.com/intentionet/netconan/blob/72824f8b351027d972f8a9a4ce3b442cda0f68ec/tests/unit/test_anonymize_files.py#L9)):*
> ```Python
> 
> from netconan.anonymize_files import FileAnonymizer, anonymize_files
> ```

Do you know how this got added? Wasn't triggered by `pre-commit run --all-files` for me. Please revert if so.

**Comment by Kircheneer** [comment]
I don't know where that comment went, but I moved the imports back to where they belong.

**Comment by Kircheneer** [comment]
> > Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)_ status: all files reviewed, 2 unresolved discussions (waiting on @Kircheneer and @sfraint)
> 
> _[`tests/unit/test_anonymize_files.py` line 9 at r3](https://reviewable.io/reviews/intentionet/netconan/186#-NW93NwC6SWSOAnpv0Ih:-NW93NwC6SWSOAnpv0Ii:b-5t9r8) ([raw file](https://github.com/intentionet/netconan/blob/72824f8b351027d972f8a9a4ce3b442cda0f68ec/tests/unit/test_anonymize_files.py#L9)):_
> 
> > ```python
> > from netconan.anonymize_files import FileAnonymizer, anonymize_files
> > ```
> 
> Do you know how this got added? Wasn't triggered by `pre-commit run --all-files` for me. Please revert if so.

Fixed!

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)* status: all files reviewed, 1 unresolved discussion (waiting on @Kircheneer and @sfraint)

**Comment by Kircheneer** [comment]
Fixed CI again now, sorry.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intentionet/netconan/186)* status: all files reviewed, 1 unresolved discussion (waiting on @Kircheneer and @sfraint)

**Pull request merged**
