### PR TITLE
Only replace stand-alone AS numbers

### PR DESCRIPTION
**Pull request by sfraint**
* Only match stand-alone AS numbers (surrounded by non-digits)
* Replace all-at-once instead of looping
* Test updates

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/54)

### CODE REVIEW

**Comment by progwriter** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_sensitive_item_removal.py, line 158 at r1](https://reviewable.io:443/reviews/intentionet/netconan/54#-L7zZTWizsQjVglhVZKX:-L7zZTWizsQjVglhVZKY:bsm9nc2) ([raw file](https://github.com/intentionet/netconan/blob/279bd5034af14f2fd5b66b15489ec3d6bc9250e5/tests/test_sensitive_item_removal.py#L158)):*
> ```Python
>     ('asdf{0}_asdf{0}asdf', ['65530']),
>     ('anonymize.{} and {}?', ['4567', '1234567']),
>     ('{}', ['12345'])
> ```

Add test where As number is at the beginning of line, followed by some stuff?

---

*[tests/test_sensitive_item_removal.py, line 184 at r1](https://reviewable.io:443/reviews/intentionet/netconan/54#-L7zZGpEXUk9JTYWxM7Q:-L7zZGpFSwzTUMhoAxnS:b-n8gjrh) ([raw file](https://github.com/intentionet/netconan/blob/279bd5034af14f2fd5b66b15489ec3d6bc9250e5/tests/test_sensitive_item_removal.py#L184)):*
> ```Python
>     ('{}{}', ['1234', '5678']),
>     ('{}000', ['1234']),
>     ('000{}', ['1234'])
> ```

Add test for numbers outside of the accepted range? I.e., larger than 4-byte AS number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_sensitive_item_removal.py, line 158 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/54#-L7zZTWizsQjVglhVZKX:-L7z_VjY8gdEAzkOM5ux:b-896fix) ([raw file](https://github.com/intentionet/netconan/blob/279bd5034af14f2fd5b66b15489ec3d6bc9250e5/tests/test_sensitive_item_removal.py#L158)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Add test where As number is at the beginning of line, followed by some stuff?
</blockquote></details>

Done.

---

*[tests/test_sensitive_item_removal.py, line 184 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/54#-L7zZGpEXUk9JTYWxM7Q:-L7z_3xF5ax3lYUI-hZu:b-bs4sop) ([raw file](https://github.com/intentionet/netconan/blob/279bd5034af14f2fd5b66b15489ec3d6bc9250e5/tests/test_sensitive_item_removal.py#L184)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Add test for numbers outside of the accepted range? I.e., larger than 4-byte AS number.
</blockquote></details>

Testing that in `test_as_number_invalid` below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/54)*

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_sensitive_item_removal.py, line 184 at r1](https://reviewable.io:443/reviews/intentionet/netconan/54#-L7zZGpEXUk9JTYWxM7Q:-L7zdb9K2pDf7tgL6Ifn:b-7z0scv) ([raw file](https://github.com/intentionet/netconan/blob/279bd5034af14f2fd5b66b15489ec3d6bc9250e5/tests/test_sensitive_item_removal.py#L184)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Testing that in `test_as_number_invalid` below.
</blockquote></details>

Ah, missed that, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54#-:-L7zdmOpiYzGTpn7ZS77:bnfp4nl)*

**Comment by dhalperi** [comment]
LGTM if LGT to Victor.

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54#-:-L8-sS8wQblHqZxfP1RJ:bqkywp1)*

**Comment by progwriter** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[netconan/sensitive_item_removal.py, line 42 at r3](https://reviewable.io:443/reviews/intentionet/netconan/54#-L8-vTfdvjDE1CnZ9JDe:-L8-vTfdvjDE1CnZ9JDf:bgdz32b) ([raw file](https://github.com/intentionet/netconan/blob/c9181ada0d66ad8c7356ca43032140f25bab2039/netconan/sensitive_item_removal.py#L42)):*
> ```Python
> 
> 
> class ASNumberAnonymizer:
> ```

For the sake of consistency with `IpAnonymizer`, make this `AsNumberAnonymizer`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[netconan/sensitive_item_removal.py, line 42 at r3](https://reviewable.io:443/reviews/intentionet/netconan/54#-L8-vTfdvjDE1CnZ9JDe:-L83A2W0bWWGre0ULN30:b-896fix) ([raw file](https://github.com/intentionet/netconan/blob/c9181ada0d66ad8c7356ca43032140f25bab2039/netconan/sensitive_item_removal.py#L42)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

For the sake of consistency with `IpAnonymizer`, make this `AsNumberAnonymizer`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intentionet/netconan/54)*

**Comment by progwriter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/54#-:-L83At5y1EEKrMwZV6MU:bnfp4nl)*

**Comment by progwriter** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/54)*

**Pull request merged**
