### PR TITLE
Allow Sensitive Line Prefixes

### LINKED ISSUE #61: Anonymizer could do better detecting nested paswords
```
set community \"<snmp community>\"
key <key>
tacacs-server host <ip> key 7 \"key\"
```

### PR DESCRIPTION
**Pull request by sfraint**
Added prefix check for sensitive line regexes.  For example, if `set community FOO` is detected as a sensitive line, then `Unrecognized Line: 1: set community FOO ...` will also be detected as a sensitive line.

Also, format detection now works correctly for passwords enclosed in quotes.

Fixes #61

---
This change is [Reviewable](https://reviewable.io/reviews/intentionet/netconan/62)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 3 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---

*[netconan/default_pwd_regexes.py, line 63 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/62#-L9g6uCG8JsvBk4h3pqm:-L9g6uCG8JsvBk4h3pqn:bvck86h) ([raw file](https://github.com/intentionet/netconan/blob/9fd62f166e46289dca8771e039e6d5fcbd2ad06a/netconan/default_pwd_regexes.py#L63)):*
> ```Python
>     [('((ikev2 )?(local|remote)-authentication pre-shared-key) \K(\S+)(?= ?.*)', 4)],
>     [('((\S )*pre-shared-key( remote| local)?( hex| \d)?) \K(\S+)(?= ?.*)', 5)],
>     [('((tacacs|radius)-server? (\S+ )*key)( \d)? \K(\S+)(?= ?.*)', 5)],
> ```

what is this? maybe a mistaken addition based on a typo I made in original bug report?

---

*[netconan/sensitive_item_removal.py, line 33 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/62#-L9g8Lfn3FAM49elt27W:-L9g8Lfn3FAM49elt27X:blrdnme) ([raw file](https://github.com/intentionet/netconan/blob/9fd62f166e46289dca8771e039e6d5fcbd2ad06a/netconan/sensitive_item_removal.py#L33)):*
> ```
> ('(\S* )*"?
> ```

Can we delete everything before `K` now? (And maybe after the end of the regex, if relevant?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/62)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/62)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/62#-:-L9gJOPWA3TGI_PGA6jh:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[netconan/default_pwd_regexes.py, line 63 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/62#-L9g6uCG8JsvBk4h3pqm:-L9gHbCJ61UEmX6qgUX7:b79glk1) ([raw file](https://github.com/intentionet/netconan/blob/9fd62f166e46289dca8771e039e6d5fcbd2ad06a/netconan/default_pwd_regexes.py#L63)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is this? maybe a mistaken addition based on a typo I made in original bug report?
</blockquote></details>

Yep, removed.

---

*[netconan/sensitive_item_removal.py, line 33 at r1](https://beta.reviewable.io/reviews/intentionet/netconan/62#-L9g8Lfn3FAM49elt27W:-L9gHdSd5BfnAhRIoezI:b-onkygy) ([raw file](https://github.com/intentionet/netconan/blob/9fd62f166e46289dca8771e039e6d5fcbd2ad06a/netconan/sensitive_item_removal.py#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ('(\S* )*"?
> ```

Can we delete everything before `K` now? (And maybe after the end of the regex, if relevant?)
</blockquote></details>

Looks like with a change to `_ALLOWED_REGEX_PREFIX` and a change to an existing default password regex we should be able to remove the leading word matches.

I have also removed the broad, trailing regexes matches.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/62)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/intentionet/netconan/62#-:-L9gJlEd1JvfDu6sNgez:bnfp4nl)*

**Pull request merged**
